# Default values for Go projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: 10.3.252.136:5000/kevinstl/lnd-kube
  tag: 0.0.18
  pullPolicy: IfNotPresent
service:
  name: lnd-kube
  type: ClusterIP
  externalPort: 10009
  internalPort: 10009
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 512Mi
probePath: /
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
terminationGracePeriodSeconds: 10

project:    #TODO: Should clean this up. Remove redundancy of network & networkSuffix
  namespace: lightning-kube-simnet
  network: simnet
  networkSuffix: -simnet
